# Generated by Django 4.2.5 on 2023-10-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_frequency", models.FloatField()),
                ("end_frequency", models.FloatField()),
                ("center_frequency", models.FloatField()),
                ("block_code", models.CharField(max_length=100)),
            ],
        ),
    ]
